### ISSUE TITLE
go get github.com/AdoHe/kube2haproxy error

### ISSUE THREAD

**Issue by marviniter** [adohe/kube2haproxy#1]
# github.com/AdoHe/kube2haproxy/util/ratelimiter
AdoHe/kube2haproxy/util/ratelimiter/ratelimiter.go:46: not enough arguments in call to rlf.queue.Pop
AdoHe/kube2haproxy/util/ratelimiter/ratelimiter.go:46: too many arguments in call to rlf.handleOne
# github.com/AdoHe/kube2haproxy/util/cache
AdoHe/kube2haproxy/util/cache/eventqueue.go:58: cannot use EventQueue literal (type *EventQueue) as type cache.Store in assignment:
	*EventQueue does not implement cache.Store (missing Resync method)

go version is go1.6.2 linux/amd64

**Comment by adohe** [comment]
@marviniter thanks for report, I will take a look tomorrow.

**Comment by marviniter** [comment]
请问一下前辈，keepalive与haproxy需要手动在服务器上面安装吧，然后，keepalive的一个vip对应一个kubernetes的service吗？

**Comment by adohe-zz** [comment]
@marviniter I just get time to fix this, and it should be fixed now. Thanks for reporting.

**Comment by marviniter** [comment]
I have a question, all traffic is through the keepavlied master node's NIC？@adohe

**Comment by adohe-zz** [comment]
Keepalived here is just used to build high available HAProxy cluster, and for your question, yes. This is not like some kind of distributed load balance way, like kube-proxy, but I do believe you can configure HAProxy to handle this better.

**Comment by marviniter** [comment]
@adohe But what should I do? Can you give me a suggestion?
