### ISSUE TITLE
which version of k8s is used in this project?

### ISSUE THREAD

**Issue by liqingshan** [AdoHe/kube2haproxy#4]
and this revision included in Godeps.json can not be found in k8s' repo.
"ImportPath": "k8s.io/kubernetes/pkg/api",
"Rev": "e9b96739d107f1b681e4d2cd09ec211fce3bbd27"

**Comment by liqingshan** [comment]
and this revision included in Godeps.json can not be found in k8s' repo.
    "ImportPath": "k8s.io/kubernetes/pkg/api",
    "Rev": "e9b96739d107f1b681e4d2cd09ec211fce3bbd27"

**Comment by adohe-zz** [comment]
@liqingshan anything I can help you? I was just too busy past few days.
